# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18proto/auth_service.proto\x12\x0b\x61uthservice"\x07\n\x05\x45mpty"D\n\x10LoginUserRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password"W\n\x11LoginUserResponse\x12\x1d\n\nauth_token\x18\x02 \x01(\tR\tauthToken\x12#\n\rrefresh_token\x18\x03 \x01(\tR\x0crefreshToken"G\n\x13RegisterUserRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password"9\n\x12GetNewTokenRequest\x12#\n\rrefresh_token\x18\x01 \x01(\tR\x0crefreshToken"]\n\x13GetNewTokenResponse\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\x12#\n\rrefresh_token\x18\x02 \x01(\tR\x0crefreshToken";\n\x16\x41uthorizeActionRequest\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken"V\n\x17\x41uthorizeActionResponse";\n\x15\x41uthorizeActionnState\x12\x0e\n\nAUTHORIZED\x10\x00\x12\x12\n\x0eNOT_AUTHORIZED\x10\x01\x32\xeb\x02\n\x0b\x41uthService\x12P\n\rSendLoginUser\x12\x1d.authservice.LoginUserRequest\x1a\x1e.authservice.LoginUserResponse"\x00\x12J\n\x10SendRegisterUser\x12 .authservice.RegisterUserRequest\x1a\x12.authservice.Empty"\x00\x12Z\n\x14GetNewTokenByRefresh\x12\x1f.authservice.GetNewTokenRequest\x1a\x1f.authservice.GetNewTokenRequest"\x00\x12\x62\n\x13SendAuthorizeAction\x12#.authservice.AuthorizeActionRequest\x1a$.authservice.AuthorizeActionResponse"\x00\x42o\n\x0f\x63om.authserviceB\x10\x41uthServiceProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x0b\x41uthservice\xca\x02\x0b\x41uthservice\xe2\x02\x17\x41uthservice\\GPBMetadata\xea\x02\x0b\x41uthserviceb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.auth_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\017com.authserviceB\020AuthServiceProtoP\001\242\002\003AXX\252\002\013Authservice\312\002\013Authservice\342\002\027Authservice\\GPBMetadata\352\002\013Authservice"
    _globals["_EMPTY"]._serialized_start = 41
    _globals["_EMPTY"]._serialized_end = 48
    _globals["_LOGINUSERREQUEST"]._serialized_start = 50
    _globals["_LOGINUSERREQUEST"]._serialized_end = 118
    _globals["_LOGINUSERRESPONSE"]._serialized_start = 120
    _globals["_LOGINUSERRESPONSE"]._serialized_end = 207
    _globals["_REGISTERUSERREQUEST"]._serialized_start = 209
    _globals["_REGISTERUSERREQUEST"]._serialized_end = 280
    _globals["_GETNEWTOKENREQUEST"]._serialized_start = 282
    _globals["_GETNEWTOKENREQUEST"]._serialized_end = 339
    _globals["_GETNEWTOKENRESPONSE"]._serialized_start = 341
    _globals["_GETNEWTOKENRESPONSE"]._serialized_end = 434
    _globals["_AUTHORIZEACTIONREQUEST"]._serialized_start = 436
    _globals["_AUTHORIZEACTIONREQUEST"]._serialized_end = 495
    _globals["_AUTHORIZEACTIONRESPONSE"]._serialized_start = 497
    _globals["_AUTHORIZEACTIONRESPONSE"]._serialized_end = 583
    _globals["_AUTHORIZEACTIONRESPONSE_AUTHORIZEACTIONNSTATE"]._serialized_start = 524
    _globals["_AUTHORIZEACTIONRESPONSE_AUTHORIZEACTIONNSTATE"]._serialized_end = 583
    _globals["_AUTHSERVICE"]._serialized_start = 586
    _globals["_AUTHSERVICE"]._serialized_end = 949
# @@protoc_insertion_point(module_scope)
